backend:
  name: git-gateway
  branch: main

media_folder: assets/images
public_folder: /assets/images

collections:
  - name: projects
    label: Projects
    folder: content/projects
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Number, name: number, widget: string }
      - { label: Name, name: name, widget: string }
      - label: Tags
        name: tags
        widget: list
        field: { label: Tag, name: tag, widget: string }
      - { label: Year, name: year, widget: string }
      - { label: Hero Image, name: hero_image, widget: image }
      - { label: Intro, name: intro, widget: text }
      - label: Case Images
        name: case_images
        widget: list
        fields:
          - { label: Image, name: image, widget: image }
          - { label: Caption, name: caption, widget: string }
      - { label: Next Project, name: next_project, widget: string }
